[project]
name = "top100-stock"
version = "0.1.0"
description = "Top 100 Companies Dashboard"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "plotly",
    "streamlit",
    "pyarrow",
]
